#!/bin/bash
# Command Line Login with API Token

echo "🔑 HEROKU API TOKEN METHOD"
echo "========================="
echo ""
echo "1. Go to: https://dashboard.heroku.com/account"
echo "2. Login with your new Heroku account"
echo "3. Scroll down to 'API Key' section"
echo "4. Click 'Regenerate API Key'"
echo "5. Copy the generated API key"
echo "6. Come back to terminal and run:"
echo ""
echo "   heroku auth:token"
echo ""
echo "7. Paste the API key when prompted"
echo "8. Then you can use command line normally:"
echo ""
echo "   heroku create mini-100prosim-platform"
echo "   heroku config:set SECRET_KEY='...'"
echo "   heroku config:set DEBUG=False"
echo "   heroku config:set ALLOWED_HOSTS=mini-100prosim-platform.herokuapp.com"
echo "   git push heroku main"
echo ""
echo "But Dashboard method is easier for MFA accounts!"
