#!/bin/bash
# Railway Deployment Script for Mini-100ProSim

echo "🚀 Railway Deployment Guide for Mini-100ProSim"
echo "=============================================="
echo ""
echo "📋 STEP 1: Push to GitHub"
echo "1. Go to GitHub.com and create a new repository named 'mini-100prosim'"
echo "2. Copy the repository URL (e.g., https://github.com/yourusername/mini-100prosim.git)"
echo ""
echo "📋 STEP 2: Add Remote and Push"
echo "Run these commands in your terminal:"
echo "git remote add origin https://github.com/yourusername/mini-100prosim.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "📋 STEP 3: Deploy on Railway"
echo "1. Go to railway.app and sign up/login"
echo "2. Click 'Deploy from GitHub repo'"
echo "3. Select your mini-100prosim repository"
echo "4. Railway will automatically detect Django and deploy!"
echo ""
echo "📋 STEP 4: Set Environment Variables"
echo "In Railway dashboard, go to Variables tab and add:"
echo "- SECRET_KEY: django-insecure-y#77%399dcbrd0jmnw#!60bl=f-iibe)=_kh-lklf=m_ptjn$)"
echo "- DEBUG: False"
echo "- ALLOWED_HOSTS: your-app-name.railway.app"
echo ""
echo "✅ Your app will be live at: https://your-app-name.railway.app"
