#!/bin/bash
# Heroku Deployment Script for Mini-100ProSim

echo "🚀 Heroku Deployment Guide for Mini-100ProSim"
echo "============================================="
echo ""
echo "📋 STEP 1: Install Heroku CLI"
echo "Download from: https://devcenter.heroku.com/articles/heroku-cli"
echo ""
echo "📋 STEP 2: Login to Heroku"
echo "heroku login"
echo ""
echo "📋 STEP 3: Create Heroku App"
echo "heroku create mini-100prosim-energy"
echo ""
echo "📋 STEP 4: Set Environment Variables"
echo "heroku config:set SECRET_KEY='django-insecure-y#77%399dcbrd0jmnw#!60bl=f-iibe)=_kh-lklf=m_ptjn$)'"
echo "heroku config:set DEBUG=False"
echo "heroku config:set ALLOWED_HOSTS=mini-100prosim-energy.herokuapp.com"
echo ""
echo "📋 STEP 5: Deploy"
echo "git push heroku main"
echo ""
echo "📋 STEP 6: Open Your App"
echo "heroku open"
echo ""
echo "✅ Your app will be live at: https://mini-100prosim-energy.herokuapp.com"
