#!/bin/bash
# DigitalOcean App Platform Deployment Guide

echo "🚀 DigitalOcean App Platform Deployment"
echo "======================================"
echo ""
echo "📋 STEP 1: Push to GitHub (same as Railway)"
echo ""
echo "📋 STEP 2: Create App on DigitalOcean"
echo "1. Go to cloud.digitalocean.com"
echo "2. Click 'Create' → 'App'"
echo "3. Connect your GitHub repository"
echo "4. Select mini-100prosim repository"
echo ""
echo "📋 STEP 3: Configure Build Settings"
echo "- Build Command: pip install -r requirements.txt"
echo "- Run Command: gunicorn config.wsgi"
echo "- Port: 8000"
echo ""
echo "📋 STEP 4: Set Environment Variables"
echo "Add in App Settings:"
echo "- SECRET_KEY: django-insecure-y#77%399dcbrd0jmnw#!60bl=f-iibe)=_kh-lklf=m_ptjn$)"
echo "- DEBUG: False"
echo "- ALLOWED_HOSTS: your-app-name.ondigitalocean.app"
echo ""
echo "✅ Your app will be live at: https://your-app-name.ondigitalocean.app"
