#!/bin/bash
# GitHub Push Commands for Mini-100ProSim

echo "🔗 STEP 1: Add GitHub Remote"
echo "Replace YOUR_USERNAME with your actual GitHub username:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/mini-100prosim.git"
echo ""
echo "🚀 STEP 2: Push to GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "✅ STEP 3: Go to Heroku Dashboard"
echo "1. Visit: https://dashboard.heroku.com/"
echo "2. Click 'New' → 'Create new app'"
echo "3. Name: mini-100prosim-energy"
echo "4. Connect to your GitHub repository"
echo "5. Set environment variables in Settings:"
echo "   - SECRET_KEY: django-insecure-y#77%399dcbrd0jmnw#!60bl=f-iibe)=_kh-lklf=m_ptjn$)"
echo "   - DEBUG: False"
echo "   - ALLOWED_HOSTS: mini-100prosim-energy.herokuapp.com"
echo "6. Deploy from Deploy tab"
echo ""
echo "🎉 Your app will be live at: https://mini-100prosim-energy.herokuapp.com"
